apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-kafka-consumer
  labels:
    app: temperature-kafka-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temperature-kafka-consumer
  template:
    metadata:
      labels:
        app: temperature-kafka-consumer
    spec:
      containers:
      - name: temperature-kafka-consumer
        image: ${YOUR_DOCKER_REGISTRY}/temperature-service:latest
        command: ["python", "kafka_consumer.py"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_SSL
          value: "true"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
