apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-scheduler
  labels:
    app: temperature-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-scheduler
  template:
    metadata:
      labels:
        app: temperature-scheduler
    spec:
      containers:
      - name: temperature-scheduler
        image: ${YOUR_DOCKER_REGISTRY}/temperature-service:latest
        command: ["python", "scheduler.py"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_SSL
          value: "true"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: IPFS_HOST
          value: "ipfs-service"
        - name: IPFS_PORT
          value: "5001"
        - name: IPFS_PROTOCOL
          value: "http"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
